# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 09:45
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import fiveapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_time', models.DateTimeField(max_length=255)),
                ('opentok_session_id', models.CharField(max_length=255)),
                ('rating_by_userA', django.contrib.postgres.fields.jsonb.JSONField()),
                ('rating_by_userB', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_uuid', models.CharField(db_index=True, default=fiveapp.models.get_uuid, max_length=63)),
                ('facebook_id', models.CharField(db_index=True, max_length=255)),
                ('firebase_id', models.CharField(db_index=True, max_length=255)),
                ('last_visited', models.DateTimeField()),
                ('fb_link', models.CharField(max_length=255)),
                ('fb_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('filters', django.contrib.postgres.fields.jsonb.JSONField()),
                ('avg_rating', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='chats',
            name='userA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userA', to='fiveapp.Users'),
        ),
        migrations.AddField(
            model_name='chats',
            name='userB',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userB', to='fiveapp.Users'),
        ),
    ]
