# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 10:18
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiveapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='rating_by_userA',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='chats',
            name='rating_by_userB',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='avg_rating',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='fb_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='filters',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
