# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiveapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='facebook_id',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
    ]
