# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiveapp', '0004_auto_20170405_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='fcm_token',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
