# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiveapp', '0006_users_app_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='notified_times',
            field=models.IntegerField(default=0),
        ),
    ]
