# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiveapp', '0007_chats_notified_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='chat_time',
            field=models.DateTimeField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='chats',
            name='notified_times',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
