# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiveapp', '0008_auto_20170411_2307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chats',
            old_name='notified_times',
            new_name='chat_notified_times',
        ),
        migrations.AddField(
            model_name='chats',
            name='rating_notified_times',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
