# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiveapp', '0009_auto_20170412_0438'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='timezone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
