# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiveapp', '0010_users_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='timezone',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
